name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - name: Install clippy e rustfmt
      run: rustup component add clippy rustfmt
    - name: Formatação (rustfmt)
      run: cargo fmt --check
    - name: Build
      run: cargo build --verbose
    - name: Clippy
      run: cargo clippy --all-targets -- -D warnings
    - name: Run tests
      run: cargo test --verbose
